# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Linux build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        sudo apt install patchelf
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Nuitka compile
      run: |
        python -m nuitka --standalone --show-progress --disable-console --onefile --plugin-enable=pyside6 --output-dir=build_output src/SimpleMangaViewerLITE.py

    - name: Archive build_output folder
      run: |
        zip -r SimpleMangaViewerLITE.zip build_output

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SimpleMangaViewerLITE
        path: SimpleMangaViewerLITE.zip
