# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        wget https://github.com/TianZerL/pyanime4k/raw/master/setup_wheel_ubuntu.sh && chmod +x setup_wheel_ubuntu.sh && ./setup_wheel_ubuntu.sh
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Nuitka compile
      run: |
        nuitka --standalone --show-progress --disable-console --onefile --plugin-enable=pyside6 --windows-icon-from-ico="icon-512.ico" --output-dir=build_output SimpleMangaViewerLITE.py

    - name: Copy pyanime4K folder
      run: |
        cp -r Lib/site-packages/pyanime4K build_output/SimpleMangaViewerLITE.dist/

    - name: Copy icon file
      run: |
        cp icon-512.png build_output/SimpleMangaViewerLITE.dist/
